title: "Jose Luis Flores"
description: "Aspiring Data Scientist & Academic Tutor"
# Website settings

# Theme
theme: jekyll-theme-cayman
custom_css: style.css

# Social links
social_links:
  - name: GitHub
    url: https://github.com/LuisF1238
  - name: LinkedIn
    url: https://www.linkedin.com/in/jose-luis-flores-645a1425a/


# Optional: Custom variables for site navigation
header_pages:
  - index.md
  - projects.md
  - about.md
  - blog.md
